-- ============================================================
-- Chronicon — Exercise Library Seed Data (~100 exercises)
-- ============================================================

insert into exercises (name, category, muscle_groups, description, instructions, is_custom) values

-- ============================================================
-- WARMUP (20)
-- ============================================================
('Jog in Place', 'warmup', '{full_body}', 'Light jogging on the spot to raise heart rate.', 'Lift knees alternately, land softly on the balls of your feet. Keep a relaxed pace.', false),
('Arm Circles', 'warmup', '{upper_body}', 'Circular shoulder mobility movement.', 'Extend arms out to the sides. Make small circles forward for 15s, then reverse.', false),
('Leg Swings (Forward)', 'warmup', '{lower_body}', 'Hip flexor and hamstring warm-up.', 'Hold a wall for balance. Swing one leg forward and back in a controlled arc. 10 reps each side.', false),
('Leg Swings (Lateral)', 'warmup', '{lower_body}', 'Hip abductor and adductor warm-up.', 'Hold a wall. Swing leg side to side across the body. 10 reps each side.', false),
('Neck Rolls', 'warmup', '{upper_body}', 'Gentle cervical spine mobilisation.', 'Drop chin to chest, slowly roll ear to shoulder, head back, other shoulder. 5 circles each direction.', false),
('Hip Circles', 'warmup', '{lower_body,core}', 'Rotational hip warm-up.', 'Hands on hips, feet shoulder-width. Draw large circles with your hips. 10 each direction.', false),
('Ankle Rolls', 'warmup', '{lower_body}', 'Ankle joint mobilisation.', 'Lift one foot off the ground, rotate the ankle clockwise then counter-clockwise. 10 each side.', false),
('Shoulder Rolls', 'warmup', '{upper_body}', 'Shoulder girdle activation.', 'Roll shoulders forward 5 times, then backward 5 times in a controlled motion.', false),
('Torso Twists', 'warmup', '{core}', 'Spinal rotation warm-up.', 'Stand with feet shoulder-width, arms extended. Rotate torso left then right, keeping hips facing forward.', false),
('Cat-Cow Stretch', 'warmup', '{core}', 'Spinal flexion and extension mobilisation.', 'On all fours, arch back up (cat), then drop belly down and lift head (cow). Breathe through each movement.', false),
('World''s Greatest Stretch', 'warmup', '{full_body}', 'Full-body mobility warm-up combining hip flexor, thoracic, and hamstring work.', 'Step forward into a lunge, place same-side hand inside foot, rotate upper body and reach skyward. Hold 2s. Alternate sides.', false),
('Inchworm', 'warmup', '{full_body}', 'Hamstring, core, and upper body warm-up combined.', 'Stand, hinge at hips, walk hands out to plank, walk feet back to hands, stand. Repeat.', false),
('Butt Kicks', 'warmup', '{lower_body}', 'Quad and glute warm-up jog variant.', 'Jog in place kicking heels up toward your glutes. Keep torso upright.', false),
('High Knees', 'warmup', '{lower_body,core}', 'Hip flexor activation and cardio primer.', 'Drive alternating knees up to hip height. Pump arms in opposition. Maintain a quick pace.', false),
('Jumping Jacks', 'warmup', '{full_body}', 'Classic full-body warm-up exercise.', 'Start with feet together and arms at sides. Jump feet out while raising arms overhead. Jump back to start.', false),
('Wrist Circles', 'warmup', '{upper_body}', 'Wrist joint warm-up.', 'Extend arms forward, make slow circles with wrists. 10 each direction.', false),
('Hip Flexor March', 'warmup', '{lower_body,core}', 'Standing hip flexor activation.', 'Lift one knee to 90° while standing tall. Hold 1 second. Alternate. Keep core engaged.', false),
('Side Shuffles', 'warmup', '{lower_body}', 'Lateral movement warm-up.', 'Lower into a quarter squat, shuffle 5 steps right, 5 steps left. Keep hips low throughout.', false),
('Thoracic Extension', 'warmup', '{upper_body}', 'Upper back mobilisation.', 'Sit on heels or stand. Clasp hands behind head, elbows wide. Gently arch back to open chest. Hold 3s, repeat 5 times.', false),
('Dynamic Lunge with Twist', 'warmup', '{full_body}', 'Hip, ankle, and thoracic warm-up.', 'Step into a forward lunge. Rotate torso toward the front leg. Step back. Alternate sides.', false),

-- ============================================================
-- CARDIO (25)
-- ============================================================
('Burpees', 'cardio', '{full_body}', 'Full-body explosive conditioning exercise.', 'From standing, drop hands to floor, jump feet back to plank, perform a push-up (optional), jump feet forward, jump up with arms overhead.', false),
('Mountain Climbers', 'cardio', '{core,full_body}', 'Core and cardio combination in plank position.', 'Start in plank. Drive one knee toward chest, then switch rapidly. Keep hips level and core braced.', false),
('Jump Rope (Invisible)', 'cardio', '{full_body}', 'Jump rope motion without equipment.', 'Mimic jumping rope: bounce lightly on balls of feet, wrists rotating in small circles at your sides.', false),
('Box Step-Ups', 'cardio', '{lower_body}', 'Elevation step cardio exercise.', 'Step one foot onto a box or step, push through heel to stand, step back down. Alternate lead leg.', false),
('Sprint in Place', 'cardio', '{full_body}', 'Maximum effort stationary sprint.', 'Drive knees up as fast as possible, pump arms hard. Go all-out for the set duration.', false),
('Broad Jumps', 'cardio', '{lower_body,full_body}', 'Explosive horizontal jump.', 'Bend knees, swing arms back, then jump forward as far as possible. Land softly. Walk back and repeat.', false),
('Lateral Bounds', 'cardio', '{lower_body}', 'Side-to-side explosive cardio.', 'Push off one foot, bound laterally, land on opposite foot. Stabilise before bounding back.', false),
('Speed Skaters', 'cardio', '{lower_body}', 'Lateral skater leap pattern.', 'Leap sideways off one foot, land on the opposite, sweep trailing leg behind. Swing arms in opposition.', false),
('Tuck Jumps', 'cardio', '{full_body,lower_body}', 'Explosive jump pulling knees to chest.', 'Jump up and tuck both knees toward chest at the peak. Land softly on balls of feet and absorb.', false),
('Star Jumps', 'cardio', '{full_body}', 'Wide jumping jack variant.', 'Jump up and simultaneously spread arms and legs wide (like a star). Land softly.', false),
('Squat Jumps', 'cardio', '{lower_body}', 'Explosive jumping squat.', 'Squat down to parallel, then explode upward, leaving the ground. Land softly back in squat position.', false),
('Bear Crawl', 'cardio', '{full_body,core}', 'Ground-based full-body cardio.', 'On all fours with knees hovering 2cm off ground. Crawl forward: right hand + left foot, then left hand + right foot.', false),
('Crab Walk', 'cardio', '{upper_body,core}', 'Seated position reverse crawl.', 'Sit with hands behind and feet in front. Lift hips. Walk backward — left hand + right foot, right hand + left foot.', false),
('Box Jumps', 'cardio', '{lower_body}', 'Explosive jump onto a box or platform.', 'Stand in front of box. Swing arms, bend knees, jump up landing softly on top. Step down carefully.', false),
('Skipping', 'cardio', '{full_body}', 'Continuous single-leg hop skipping pattern.', 'Skip forward alternating feet — step, hop, step, hop. Swing opposite arm with each step.', false),
('Stair Climbs', 'cardio', '{lower_body}', 'Stair-climbing cardio (or step platform).', 'Walk or run up stairs, one step at a time or skipping steps. Control descent.', false),
('Jump Lunges', 'cardio', '{lower_body}', 'Explosive alternating lunge jumps.', 'Start in a lunge. Jump and switch legs in the air, landing in the opposite lunge. Absorb landing.', false),
('Bicycle Sprint', 'cardio', '{core,lower_body}', 'Fast bicycle crunch for cardio and core.', 'Lie on back, hands behind head. Drive one knee to chest while rotating opposite elbow toward it. Switch rapidly.', false),
('Plank to Down Dog', 'cardio', '{full_body,upper_body}', 'Flowing plank to downward dog.', 'Start in plank. Push hips up into downward-facing dog (inverted V). Return to plank. Repeat rhythmically.', false),
('Diagonal Mountain Climbers', 'cardio', '{core,full_body}', 'Oblique-targeted mountain climber variation.', 'From plank, drive one knee diagonally toward the opposite elbow. Alternate sides rapidly.', false),
('Shuttle Run', 'cardio', '{full_body}', 'Short-distance sprint and change of direction drill.', 'Mark two points ~5m apart. Sprint to one, touch, sprint back. Repeat continuously.', false),
('Jumping Lunges with Twist', 'cardio', '{lower_body,core}', 'Explosive lunge with added rotation.', 'In lunge, twist torso toward front knee. Jump and switch legs, twist to the new front knee.', false),
('Explosive Push-Up', 'cardio', '{upper_body,full_body}', 'Plyometric push-up with hands leaving the ground.', 'Perform a push-up and push explosively to lift hands off the floor at the top. Land with soft elbows.', false),
('Wall Balls', 'cardio', '{full_body}', 'Squat + overhead throw (bodyweight version: air squat + arms overhead).', 'Squat, then explode up driving arms overhead as if throwing a ball at a wall above you. Catch and repeat.', false),
('Double Unders (Single Jump Variation)', 'cardio', '{full_body}', 'High jump rope cardio drill.', 'Jump with maximal height on each rep, keeping rope (or air rotation) moving fast. Focus on quick wrist rotation.', false),

-- ============================================================
-- STRENGTH (35)
-- ============================================================
('Push-Ups', 'strength', '{upper_body}', 'Classic upper body pressing movement.', 'Start in plank with hands slightly wider than shoulders. Lower chest to floor, push back up. Keep body straight.', false),
('Squats', 'strength', '{lower_body}', 'Fundamental lower body movement.', 'Stand with feet shoulder-width. Bend knees and push hips back until thighs are parallel to floor. Drive back up through heels.', false),
('Lunges', 'strength', '{lower_body}', 'Single-leg lower body strength exercise.', 'Step forward with one leg, lower until both knees are at 90°. Push back to start. Alternate legs.', false),
('Glute Bridges', 'strength', '{lower_body,core}', 'Hip extension targeting glutes and hamstrings.', 'Lie on back, knees bent, feet flat. Drive hips up by squeezing glutes. Hold at the top 1s, lower slowly.', false),
('Plank', 'strength', '{core}', 'Isometric core stability exercise.', 'Hold a push-up position on forearms. Keep body in a straight line from head to heels. Brace abs and squeeze glutes.', false),
('Side Plank', 'strength', '{core}', 'Lateral core stability on one forearm.', 'Lie on side, forearm on floor below shoulder. Lift hips to form a straight line. Hold. Switch sides.', false),
('Diamond Push-Ups', 'strength', '{upper_body}', 'Tricep-focused push-up variation.', 'Place hands close together forming a diamond shape. Lower chest toward hands, push up. Keep elbows tucked.', false),
('Wide Push-Ups', 'strength', '{upper_body}', 'Chest-focused wide-grip push-up.', 'Place hands wider than shoulder-width. Lower chest to floor and push back up. Elbows flare out slightly.', false),
('Pike Push-Ups', 'strength', '{upper_body}', 'Shoulder-focused overhead push movement.', 'Form an inverted V (down dog position). Bend elbows to lower head toward floor, push back up.', false),
('Tricep Dips', 'strength', '{upper_body}', 'Bench or floor tricep extension.', 'Hands on edge of bench behind you, fingers forward. Lower hips bending elbows to 90°. Push back up.', false),
('Sit-Ups', 'strength', '{core}', 'Abdominal crunch to full sit-up.', 'Lie on back, knees bent, feet flat. Curl torso all the way up to knees. Lower under control.', false),
('Crunches', 'strength', '{core}', 'Shortened-range abdominal isolation.', 'Lie on back, knees bent. Curl upper back off floor using abs. Lower slowly. Do not pull neck.', false),
('Leg Raises', 'strength', '{core}', 'Lower abdominal hip flexor exercise.', 'Lie on back, legs straight. Raise legs to 90°, lower slowly without letting feet touch the floor.', false),
('Russian Twists', 'strength', '{core}', 'Rotational core exercise.', 'Sit with knees bent, feet off floor, leaning back 45°. Rotate torso left then right. Touch floor each side.', false),
('Superman', 'strength', '{lower_body,upper_body}', 'Posterior chain extension on the floor.', 'Lie face down, arms extended. Simultaneously lift chest, arms, and legs off the floor. Hold 2s. Lower.', false),
('Dead Bug', 'strength', '{core}', 'Anti-extension core stability drill.', 'Lie on back, arms up, knees at 90°. Lower opposite arm and leg to the floor together. Return. Switch.', false),
('Bird Dog', 'strength', '{core}', 'Core stability and balance on all fours.', 'On hands and knees. Extend opposite arm and leg together until straight. Hold 2s. Return. Alternate.', false),
('Wall Sit', 'strength', '{lower_body}', 'Isometric quad and glute hold.', 'Lean back against a wall, slide down until thighs are parallel to the floor. Hold for the set duration.', false),
('Single-Leg Glute Bridge', 'strength', '{lower_body,core}', 'Unilateral glute bridge for extra challenge.', 'Lie on back, one knee bent foot flat, other leg extended. Drive hips up on the planted foot. Hold 1s. Repeat per side.', false),
('Step-Ups', 'strength', '{lower_body}', 'Box or stair single-leg step-up.', 'Step one foot onto a box, push through heel to stand. Step down. Complete all reps one side, switch.', false),
('Reverse Lunges', 'strength', '{lower_body}', 'Step-back lunge variation.', 'Step one foot back, lower rear knee toward floor. Push through front heel to stand. Alternate.', false),
('Sumo Squats', 'strength', '{lower_body}', 'Wide-stance squat targeting inner thighs.', 'Stand wide, toes pointed out 45°. Lower hips between heels. Drive through heels to stand.', false),
('Calf Raises', 'strength', '{lower_body}', 'Standing calf isolation.', 'Stand on edge of step or flat floor. Rise onto toes, hold 1s, lower slowly. Use wall for balance if needed.', false),
('Hollow Body Hold', 'strength', '{core}', 'Full-body tension core exercise.', 'Lie on back. Lift shoulders and legs off floor, arms overhead or at sides. Press lower back into floor. Hold.', false),
('V-Ups', 'strength', '{core}', 'Full sit-up with straight legs.', 'Lie flat, arms overhead, legs straight. Fold body like a jackknife, reaching hands to feet. Lower under control.', false),
('Plank Up-Downs', 'strength', '{core,upper_body}', 'Alternating between forearm and full plank.', 'Start in forearm plank. Push up to full plank one arm at a time. Lower back down. Alternate lead arm.', false),
('Hip Thrusts', 'strength', '{lower_body}', 'Heavy glute drive from a floor or bench position.', 'Shoulders on bench, feet flat. Drive hips up by squeezing glutes. Body forms a straight line at top. Lower slowly.', false),
('Nordic Curls', 'strength', '{lower_body}', 'Hamstring eccentric bodyweight curl.', 'Kneel with feet anchored. Lower body forward by resisting with hamstrings as long as possible. Catch yourself, push back.', false),
('Handstand Hold (Wall)', 'strength', '{upper_body,core}', 'Inverted shoulder press endurance hold.', 'Kick up to a wall handstand. Find balance with arms straight. Hold for set duration. Core and glutes tight.', false),
('L-Sit Hold', 'strength', '{core,upper_body}', 'Compressed L-sit on parallel bars or floor.', 'Support weight on straight arms, legs extended parallel to floor. Hold for set duration. Flex quads.', false),
('Inverted Row (Table)', 'strength', '{upper_body}', 'Bodyweight row using a table for pulling.', 'Lie under a sturdy table, grab edge, body straight. Pull chest up to table. Lower slowly.', false),
('Pike Hold', 'strength', '{upper_body,core}', 'Elevated hip holds for shoulder and core strength.', 'Place feet on a box, walk hands close. Body forms an inverted V. Hold, pressing through shoulders.', false),
('Curtsy Lunge', 'strength', '{lower_body}', 'Cross-behind lunge targeting glutes.', 'Step one foot diagonally behind and across. Lower until front thigh is near parallel. Return. Alternate.', false),
('Lateral Lunges', 'strength', '{lower_body}', 'Wide side step into a single-leg squat.', 'Step wide to one side, bend that knee and push hips back, keeping other leg straight. Return to center. Alternate.', false),
('Isometric Push-Up Hold', 'strength', '{upper_body}', 'Push-up held at bottom or mid position.', 'Lower into the push-up position and hold with arms at 90°. Keep body rigid. Hold for set duration.', false),

-- ============================================================
-- MOBILITY (20)
-- ============================================================
('Child''s Pose', 'mobility', '{lower_body,upper_body}', 'Restorative hip and thoracic stretch.', 'Kneel and sit hips back toward heels, arms extended forward on the floor. Hold. Breathe into lower back.', false),
('Pigeon Pose', 'mobility', '{lower_body}', 'Deep hip flexor and glute stretch.', 'From plank, bring one shin forward parallel to hips. Lower down. Keep hips square. Hold each side.', false),
('Downward Dog', 'mobility', '{full_body}', 'Hamstring and calf stretch with shoulder opening.', 'Press hands into floor, hips high forming an inverted V. Alternate pressing heels toward floor. Hold and breathe.', false),
('Standing Quad Stretch', 'mobility', '{lower_body}', 'Standing quad and hip flexor hold.', 'Stand on one leg, pull opposite foot toward glute. Hold ankle, keep knees together, stand tall. Alternate.', false),
('Seated Hamstring Stretch', 'mobility', '{lower_body}', 'Long-sit hamstring hold.', 'Sit with legs straight in front. Reach toward feet, hinging at hips not rounding spine. Hold.', false),
('Seated Butterfly', 'mobility', '{lower_body}', 'Inner thigh and groin static stretch.', 'Sit with soles of feet together, knees dropped to sides. Gently press knees toward floor. Hold.', false),
('Spinal Twist (Seated)', 'mobility', '{core}', 'Thoracic and lumbar rotational stretch.', 'Sit with legs extended. Cross one foot over the other knee. Rotate torso toward bent knee, hand on floor behind. Hold.', false),
('Shoulder Cross Stretch', 'mobility', '{upper_body}', 'Rear deltoid and shoulder stretch.', 'Pull one arm horizontally across chest. Use opposite hand to increase stretch. Hold each side.', false),
('Chest Opener', 'mobility', '{upper_body}', 'Anterior chest and shoulder stretch.', 'Clasp hands behind back, squeeze shoulder blades, lift arms slightly. Hold while breathing into chest.', false),
('Hip Flexor Kneeling Stretch', 'mobility', '{lower_body}', 'Kneeling lunge hip flexor hold.', 'In a half-kneeling position (one knee on floor). Shift hips forward to feel stretch in rear hip flexor. Hold each side.', false),
('Calf Stretch (Wall)', 'mobility', '{lower_body}', 'Gastrocnemius and soleus wall stretch.', 'Press hands on wall. Step one foot back, heel pressed flat. Hold. Bend rear knee slightly to target soleus.', false),
('Doorway Chest Stretch', 'mobility', '{upper_body}', 'Pectoral stretch using a wall or frame.', 'Place forearm on a wall, elbow at 90°. Rotate body away to feel stretch across chest. Hold each side.', false),
('Lat Stretch (Overhead Side Bend)', 'mobility', '{upper_body,core}', 'Lateral lat and oblique stretch.', 'Stand, raise one arm overhead. Side bend away from that arm. Hold. Alternate sides.', false),
('Figure-4 Glute Stretch', 'mobility', '{lower_body}', 'Seated or lying piriformis and glute stretch.', 'Lie on back, cross one ankle over the opposite knee. Pull both legs toward chest. Hold each side.', false),
('Thread the Needle', 'mobility', '{upper_body,core}', 'Thoracic rotation and shoulder stretch on all fours.', 'On hands and knees. Slide one arm under body (palm up) rotating thoracic spine. Lower shoulder to floor. Hold. Alternate.', false),
('90-90 Hip Stretch', 'mobility', '{lower_body}', 'Dual-position hip capsule stretch.', 'Sit with both legs in 90° angles (front shin and rear shin). Hold, then rotate to switch which leg is in front.', false),
('Neck Side Stretch', 'mobility', '{upper_body}', 'Upper trap and cervical lateral stretch.', 'Tilt ear to shoulder. Optionally place hand on head for gentle added pressure. Hold each side.', false),
('IT Band Stretch (Standing)', 'mobility', '{lower_body}', 'Iliotibial band and outer hip stretch.', 'Cross one leg behind the other. Lean laterally away from crossed leg. Hold each side.', false),
('Forearm Stretch', 'mobility', '{upper_body}', 'Wrist flexor and forearm stretch.', 'Extend one arm forward, palm up. Use other hand to gently pull fingers back. Hold. Alternate.', false),
('Lower Back Cat-Cow (Deep Hold)', 'mobility', '{core}', 'Sustained lumbar flexion and extension.', 'On all fours. Arch back upward and hold 5s (cat). Then drop belly and lift head and hold 5s (cow). Repeat slowly.', false);
